import { Staff, PostRequirement } from './types';

export const allStaff: Staff[] = [
  { id: '300045', name: 'Shebli Ahammad', role: 'Supervisor', permanentGroup: 'C', subSection: 'security supervisor', offDay: 'Saturday' },
  { id: '300053', name: 'Kazi Azizul Haque', role: 'Guard', permanentGroup: 'B', subSection: 'Post-1(Main Gate)', offDay: 'Saturday' },
  { id: '300057', name: 'Jasim Uddin', role: 'Guard', permanentGroup: 'A', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Tuesday' },
  { id: '300060', name: 'Md. Jamal Miah', role: 'Guard', permanentGroup: 'A', subSection: 'Post-1(Main Gate)', offDay: 'Sunday' },
  { id: '301968', name: 'Md. Rahmat Ali', role: 'Guard', permanentGroup: 'C', subSection: 'Post-11(Bangadoba Godawan Bacside)', offDay: 'Thursday' },
  { id: '301835', name: 'Md. Abdul Zalil', role: 'Guard', permanentGroup: 'A', subSection: 'Post-11(Bangadoba Godawan Bacside)', offDay: 'Friday' },
  { id: '300073', name: 'Fajor Rahman', role: 'Guard', permanentGroup: 'Reliever', subSection: 'SM Agro', offDay: 'Tuesday' },
  { id: '300082', name: 'Angura Khatun', role: 'LadyGuard', permanentGroup: 'A', subSection: 'Post-12 (Female Quarter Gate)', offDay: 'Wednesday' },
  { id: '300081', name: 'Md. Shafiqul Islam', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-6 + Shift- C', offDay: 'Saturday' },
  { id: '300914', name: 'Amena Begum', role: 'LadyGuard', permanentGroup: 'B', subSection: 'Post-1(Main Gate)', offDay: 'Friday' },
  { id: '300915', name: 'Abul Kalam', role: 'Guard', permanentGroup: 'A', subSection: 'Post-8 (Unit-01 middle Point)', offDay: 'Saturday' },
  { id: '301098', name: 'Abdul Ahad', role: 'Guard', permanentGroup: 'C', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Saturday' },
  { id: '301129', name: 'Toslim Miah', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Yarn Delivery', offDay: 'Friday' },
  { id: '301133', name: 'Jalal Miah', role: 'Guard', permanentGroup: 'C', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Friday' },
  { id: '304151', name: 'Md. Suhel Ahmod Sumon', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-10', offDay: 'Wednesday' },
  { id: '304743', name: 'Md. Dulal Miah', role: 'Guard', permanentGroup: 'A', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Monday' },
  { id: '305043', name: 'Md. Golam Rabbani', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-5 + Shift- B', offDay: 'Tuesday' },
  { id: '305675', name: 'Abinash Roy', role: 'Guard', permanentGroup: 'B', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Sunday' },
  { id: '307256', name: 'Md. Tarekul Islam Bhuyan', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-2,4,6,RG-1&2', offDay: 'Saturday' },
  { id: '309165', name: 'Md. Ishaque', role: 'Officer', permanentGroup: 'General', subSection: 'Security Officer', offDay: 'Friday' },
  { id: '309182', name: 'Md. Habibur Rahman', role: 'Guard', permanentGroup: 'B', subSection: 'Post-1(Main Gate)', offDay: 'Monday' },
  { id: '309111', name: 'Swapna Akter', role: 'LadyGuard', permanentGroup: 'C', subSection: 'Post-12 (Female Quarter Gate)', offDay: 'Saturday' },
  { id: '309666', name: 'Md. Soab Miah', role: 'Guard', permanentGroup: 'A', subSection: 'Post-3 (Finished Godown Backside)', offDay: 'Thursday' },
  { id: '309893', name: 'Md. Al Amin', role: 'Guard', permanentGroup: 'C', subSection: 'Post-1(Main Gate)', offDay: 'Tuesday' },
  { id: '311522', name: 'Md. Wahid Miah', role: 'Guard', permanentGroup: 'C', subSection: 'Post-8 (Unit-01 middle Point)', offDay: 'Sunday' },
  { id: '312292', name: 'Md. Sohidul Islam Sumon', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-07 & 08', offDay: 'Monday' },
  { id: '312613', name: 'Md. Hedayat Ullah Talukder', role: 'Supervisor', permanentGroup: 'B', subSection: 'security supervisor', offDay: 'Thursday' },
  { id: '312775', name: 'Bijoy Achargee', role: 'Guard', permanentGroup: 'B', subSection: 'Post-10 (Bangadoba Main Gate)', offDay: 'Thursday' },
  { id: '312945', name: 'Rajo', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-5 + Shift- C', offDay: 'Sunday' },
  { id: '313107', name: 'Amrite Paul', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-01', offDay: 'Thursday' },
  { id: '313178', name: 'Abul Kalam', role: 'Guard', permanentGroup: 'A', subSection: 'Device Checker', offDay: 'Friday' },
  { id: '313453', name: 'Ponir Mia Talukder', role: 'Guard', permanentGroup: 'B', subSection: 'Post-3 (Finished Godown Backside)', offDay: 'Wednesday' },
  { id: '313452', name: 'Dulal Ahmed Abdullah', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Technical Mess Supervice', offDay: 'Wednesday' },
  { id: '313454', name: 'Mijanur Rahman Sahed', role: 'Guard', permanentGroup: 'B', subSection: 'Post-8 (Unit-01 middle Point)', offDay: 'Wednesday' },
  { id: '313538', name: 'Bhabatus Paul', role: 'Guard', permanentGroup: 'B', subSection: 'Post-7 (Westage Tin Shad)', offDay: 'Monday' },
  { id: '313539', name: 'Md. Lipul Miah', role: 'Guard', permanentGroup: 'A', subSection: 'Post-7 (Westage Tin Shad)', offDay: 'Monday' },
  { id: '313537', name: 'Shamananda Das', role: 'Guard', permanentGroup: 'B', subSection: 'Device Checker', offDay: 'Monday' },
  { id: '314020', name: 'Parboti Koiri', role: 'LadyGuard', permanentGroup: 'A', subSection: 'Post-1(Main Gate)', offDay: 'Tuesday' },
  { id: '314199', name: 'Ruma Begum', role: 'LadyGuard', permanentGroup: 'B', subSection: 'Post-12 (Female Quarter Gate)', offDay: 'Thursday' },
  { id: '314198', name: 'Abdul Malak Rakib', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-4 + Shift- C', offDay: 'Friday' },
  { id: '314196', name: 'Majaharul Islam', role: 'Supervisor', permanentGroup: 'A', subSection: 'security supervisor', offDay: 'Monday' },
  { id: '314356', name: 'Saed', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-03 & Device Checker', offDay: 'Thursday' },
  { id: '314359', name: 'Md. Sakib Miah', role: 'Guard', permanentGroup: 'C', subSection: 'Device Checker', offDay: 'Sunday' },
  { id: '314478', name: 'Rashedul Islam', role: 'Guard', permanentGroup: 'Reliever', subSection: 'R-Cotton Godown -01', offDay: 'Saturday' },
  { id: '314681', name: 'Shek Md. Jasim Uddin', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-2 + Shift- B', offDay: 'Sunday' },
  { id: '314842', name: 'Mst. Mafiga Begum', role: 'LadyGuard', permanentGroup: 'Reliever', subSection: 'Reliever + Post-01&12', offDay: 'Sunday' },
  { id: '314841', name: 'Md. Isuf Khan', role: 'Guard', permanentGroup: 'A', subSection: 'Post-1(Main Gate)', offDay: 'Wednesday' },
  { id: '314910', name: 'Md. Murshed Alam Khan', role: 'Guard', permanentGroup: 'C', subSection: 'Post-3 (Finished Godown Backside)', offDay: 'Wednesday' },
  { id: '315048', name: 'Md. Nazrul Islam Chowdhury', role: 'Guard', permanentGroup: 'Reliever', subSection: 'R-Cotton Godown -02', offDay: 'Tuesday' },
  { id: '315049', name: 'Md. Anamul Jommader', role: 'Guard', permanentGroup: 'C', subSection: 'Post-1(Main Gate)', offDay: 'Tuesday' },
  { id: '315465', name: 'Md. Shah Alam Miah', role: 'Guard', permanentGroup: 'C', subSection: 'Post-7 (Westage Tin Shad)', offDay: 'Saturday' },
  { id: '315467', name: 'Piyad Mia', role: 'Guard', permanentGroup: 'B', subSection: 'Post-11 (Bangadoba Godawan Bacside)', offDay: 'Sunday' },
  { id: '315466', name: 'Md. Sahinoor Rahman', role: 'Guard', permanentGroup: 'Reliever', subSection: 'Post-2 + Shift- C', offDay: 'Sunday' },
];

export const postRequirements: PostRequirement[] = [
  { id: 'p1', name: 'Post-1(Main Gate)', shiftCounts: { A: 2, B: 2, C: 2, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['314842', '313107'] },
  { id: 'p2', name: 'Post-2', shiftCounts: { A: 0, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['307256'] },
  { id: 'p3', name: 'Post-3 (Finished Godown Backside)', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['314356'] },
  { id: 'p4', name: 'Post-4', shiftCounts: { A: 0, B: 0, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['307256'] },
  { id: 'p5', name: 'Post-5', shiftCounts: { A: 0, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['315589'] },
  { id: 'p6', name: 'Post-6', shiftCounts: { A: 0, B: 0, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['307256'] },
  { id: 'p7', name: 'Post-7 (Westage Tin Shad)', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['312292'] },
  { id: 'p8', name: 'Post-8 (Unit-01 middle Point)', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['312292'] },
  { id: 'p10', name: 'Post-10 (Bangadoba Main Gate)', shiftCounts: { A: 2, B: 2, C: 2, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['304151'] },
  { id: 'p11', name: 'Post-11 (Bangadoba Godawan Bacside)', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['315589'] },
  { id: 'p12', name: 'Post-12 (Female Quarter Gate)', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['314842'] },
  { id: 'dev', name: 'Device Checker', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['314356'] },
  { id: 'sup', name: 'security supervisor', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 } },
  { id: 'tech', name: 'Technical Mess Supervice', shiftCounts: { A: 1, B: 1, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['315589'] },
  { id: 'rcotton', name: 'R-Cotton Godown', shiftCounts: { A: 0, B: 0, C: 1, General: 0, Reliever: 0, Leave: 0, OT: 0 }, supportPersons: ['307256'] },
  { id: 'yarn', name: 'Yarn Delivery', shiftCounts: { A: 1, B: 0, C: 0, General: 0, Reliever: 0, Leave: 0, OT: 0 } },
  { id: 'agro', name: 'SM Agro', shiftCounts: { A: 1, B: 0, C: 0, General: 0, Reliever: 0, Leave: 0, OT: 0 } },
  { id: 'officer', name: 'Security Officer', shiftCounts: { A: 0, B: 0, C: 0, General: 1, Reliever: 0, Leave: 0, OT: 0 } },
];
